[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "CYwQUovV28"
weight = 1

[[main]]
name = "Livros"
pageRef = "livros"
identifier = "aS5b0eLsPN"
weight = 2

[[main]]
name = "Contos"
url = "https://escritos.msmelo.blog/contos"
identifier = "contos-sub"
weight = 3

[[main]]
name = "Newsletter"
url = "https://marciosmelo.substack.com"
identifier = "newsletter-main"
weight = 4

[[main]]
name = "Blogroll"
pageRef = "/blogroll"
identifier = "ihvVhq0Ho2"
weight = 5

[[main]]
name = "Sobre"
pageRef = "/sobre"
identifier = "oxhUFdW53b"
weight = 6

[[main]]
pre = "rss"
url = "https://msmelo.blog/index.xml"
identifier = "8gTiR4lXGf"
weight = 9999

[[main]]
pre = "mastodon"
url = "https://bolha.one/@msmelo"
identifier = "k3GdUHWXE1"
weight = 9999

[[main]]
pre = "substack"
url = "https://marciosmelo.substack.com"
identifier = "FBUHAsXrD7"
weight = 9999

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Assine minha newsletter"
   url = "https://marciosmelo.substack.com"
   weight = 20

 [[footer]]
   name = "Subscribe to RSS"
   url = "https://msmelo.blog/index.xml"
   weight = 30
   